name: Release

on:
  push:
    branches: [release/*]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Read version to release from the changelog
        id: next-release
        uses: cucumber-actions/changelog-action@v1.3
        with:
          args: latest
      - name: Set version environment variable
        run: echo "version"=${{ steps.next-release.outputs.result }} > $GITHUB_ENV
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - uses: cucumber-actions/publish-rubygem@v1.0.0
        with:
          rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
      - name: read release notes from the changelog
        id: release-notes
        uses: cucumber-actions/changelog-action@v1.3
        with:
          args: show ${{ env.version }}
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat >${{ runner.temp }}/notes << "EOT"
          ${{ steps.release-notes.outputs.result }}
          EOT
          gh release create \
            --notes-file ${{ runner.temp }}/notes \
            --title v${{ env.version }} \
            --target pre-release/v${{ env.version }} \
            v${{ env.version }}